import { Nunito } from "next/font/google";
import "@/app/global.css";
import INavigation from "@/design-components/INavigation/INavigation";
import { AuthProvider } from "@/context/AuthContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-nunito`}>
        <AuthProvider>
          <header>
            <INavigation />
          </header>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
